### ISSUE TITLE
Error in importing config.py 

### ISSUE THREAD

**Issue by decoder746** [oscarknagg/few-shot#24]
I cloned your repository and then ran `pip install -r requirements.txt`. Downloaded the minImageNet and put in the directory `./data/miniImageNet/images`. Changed the `DATA_PATH` in `config.py` to `"./data/"`. 
But when I run the command `python3 scripts/prepare_mini_imagenet.py` while staying in the root directory I get the error :- 
```
Traceback (most recent call last):
  File "scripts/prepare_mini_imagenet.py", line 16, in <module>
    from config import DATA_PATH
ModuleNotFoundError: No module named 'config'
```

@oscarknagg could you tell where the error is.

**Comment by zhangyikaii** [comment]
You can add the following code to where the error occurred:
```python
import sys
sys.path.append("..")
sys.path.extend([os.path.join(root, name) for root, dirs, _ in os.walk("../") for name in dirs])
```
